services:
  storage:
    container_name: vault-storage
    build:
      context: ./server
    volumes:
      - family-tree-data:/data
    restart: unless-stopped

  app:
    container_name: vault-app
    build: .
    ports:
      - "3939:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  family-tree-data:
